/**
 * Generates buyer + seller Ethereum wallets and a JWT secret, writes to .env
 *
 * Run: npm run generate-wallets
 *
 * After running, you need to fund the BUYER wallet with testnet USDC:
 *   1. Copy the BUYER_ADDRESS printed below
 *   2. Go to https://faucet.circle.com/
 *   3. Select "Base Sepolia" network
 *   4. Paste the BUYER_ADDRESS and request USDC
 */

import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Generate buyer wallet (the agent/client that pays)
const buyerKey = generatePrivateKey();
const buyerAccount = privateKeyToAccount(buyerKey);

// Generate seller wallet (the server that receives payments)
const sellerKey = generatePrivateKey();
const sellerAccount = privateKeyToAccount(sellerKey);

// Generate JWT secret (shared with PostgREST via docker-compose)
const jwtSecret = "super-secret-jwt-key-for-agentdb-test-only-32chars!!";

const envContent = `# Generated by: npm run generate-wallets
# Buyer wallet (the "agent" paying for project leases)
BUYER_PRIVATE_KEY=${buyerKey}
BUYER_ADDRESS=${buyerAccount.address}

# Seller wallet (the "AgentDB server" receiving payments)
SELLER_PRIVATE_KEY=${sellerKey}
SELLER_ADDRESS=${sellerAccount.address}

# JWT secret (must match PGRST_JWT_SECRET in docker-compose.yml)
JWT_SECRET=${jwtSecret}
`;

const envPath = join(__dirname, "..", ".env");
writeFileSync(envPath, envContent);

console.log("Wallets generated and written to .env\n");
console.log("  Buyer address:  ", buyerAccount.address);
console.log("  Seller address: ", sellerAccount.address);
console.log("  JWT secret:     ", jwtSecret.slice(0, 20) + "...");
console.log("");
console.log("NEXT STEP: Fund the buyer wallet with testnet USDC");
console.log("  1. Go to https://faucet.circle.com/");
console.log("  2. Select 'Base Sepolia' network");
console.log("  3. Paste this address:", buyerAccount.address);
console.log("  4. Request USDC");
console.log("");
console.log("Then:");
console.log("  npm run docker:up      # Start Postgres + PostgREST");
console.log("  npm run server         # Terminal 1: x402 gateway");
console.log("  npm run test           # Terminal 2: agent simulation");
