/**
 * Generates buyer + seller Ethereum wallets and writes them to .env
 *
 * Run: npm run generate-wallets
 *
 * After running, you need to fund the BUYER wallet with testnet USDC:
 *   1. Copy the BUYER_ADDRESS printed below
 *   2. Go to https://faucet.circle.com/
 *   3. Select "Base Sepolia" network
 *   4. Paste the BUYER_ADDRESS and request USDC
 */

import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Generate buyer wallet (the agent/client that pays)
const buyerKey = generatePrivateKey();
const buyerAccount = privateKeyToAccount(buyerKey);

// Generate seller wallet (the server that receives payments)
const sellerKey = generatePrivateKey();
const sellerAccount = privateKeyToAccount(sellerKey);

const envContent = `# Generated by: npm run generate-wallets
# Buyer wallet (the "agent" paying for DB operations)
BUYER_PRIVATE_KEY=${buyerKey}
BUYER_ADDRESS=${buyerAccount.address}

# Seller wallet (the "AgentDB server" receiving payments)
SELLER_PRIVATE_KEY=${sellerKey}
SELLER_ADDRESS=${sellerAccount.address}

# AWS (server-side only — the client never sees these)
AWS_PROFILE=kychee
AWS_REGION=us-east-1
`;

const envPath = join(__dirname, "..", ".env");
writeFileSync(envPath, envContent);

console.log("Wallets generated and written to .env\n");
console.log("  Buyer address:  ", buyerAccount.address);
console.log("  Seller address: ", sellerAccount.address);
console.log("");
console.log("NEXT STEP: Fund the buyer wallet with testnet USDC");
console.log("  1. Go to https://faucet.circle.com/");
console.log("  2. Select 'Base Sepolia' network");
console.log("  3. Paste this address:", buyerAccount.address);
console.log("  4. Request USDC");
console.log("");
console.log("Once funded, run the test:");
console.log("  Terminal 1: npm run server");
console.log("  Terminal 2: npm run test");
